name=input("what is your name??-")
print("Assalmualikum",name,"this is a marks calculator for subjects")
print("i will ask for marks of your bio/math,physics and chemistry subject and will calculate percentage and grade for you and check whether you are pass or not")
answer=input("are you ready? yes/no-")
if answer== "yes": 
    print("welcome",name)
    biologymath=int(input("what is your number in biology/math subject? out of 100?-"))
    physics=int(input("what is your number in physics? out of 100?-"))
    chemistry=int(input("what is your number in chemistry? out of 100?-"))
    print("obtained marks=",biologymath+physics+chemistry,)
    marksobtained=(biologymath+physics+chemistry)
    print("Total marks=300")
    total=(300)
    print("percentage=",marksobtained/total * 100,"%")
    percentage=(marksobtained/total * 100)
    if percentage>=50: print("Status=Passed")
    else:print("Status=Failed")
    
    if percentage>=90: print("Grade=A++")
    elif percentage>=80: print("Grade=A+")
    elif percentage>=70: print("Grade=A")
    elif percentage>=60: print("Grade=B")
    elif percentage>=50: print("Grade=C")
    else: print ("Grade=F")
    print("thank you for using this calcultor",name,)
    print("made by Gul Hussain ;D")
elif answer=="no": 
    print("Allah hafiz",name)